### ISSUE TITLE
Enter key to send message

### ISSUE THREAD

**Issue by Gr8z** [Gr8z/ChatBotProject#1]
Right now, you have to press the send key, It would be nice if we can press ENTER key to send a message.

**Comment by SaadAhmadSaddiqui** [comment]
Solved

**Comment by Gr8z** [comment]
When pressing enterkey, you hear the windows error sound.

**Comment by SaadAhmadSaddiqui** [comment]
Removed the error sound.

**Comment by Gr8z** [comment]
Tested and fixed, thanks bro
