### ISSUE TITLE
Bot Start-up message

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#10]
The Bot should say Hi/Hello as soon as the code is debugged, along with a start-up question like:
How may I help You, Today?
or
How are you doing today?
![image](https://cloud.githubusercontent.com/assets/27805889/25293965/23946f30-26ee-11e7-8df9-fe06435fb497.png)
The shown text in the screen-short above is only available once the user clicks the send button.To avoid this conflict which is made by a blank screen with out any instructions or steps to be followed by s new user of the application/ program.

**Comment by SaadAhmadSaddiqui** [comment]
#11 Similar to that issue. Solved already.
