### ISSUE TITLE
Hello as a start-up message 

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#11]
"Hello" is not being recognized by the BOT as a start-up message. 
It displays this message!
![image](https://cloud.githubusercontent.com/assets/27805889/25294099/be419512-26ee-11e7-8cb1-4e4a879ccbd9.png)
This makes the BOT look really silly....
But "Hi" as a start-up message work really well.

**Comment by Gr8z** [comment]
Please assign this to me, I'll get it done.

**Comment by Gr8z** [comment]
It looks like this happens when you type a message when the bot is loading. Once we put a loading screen in this won't happen again.

**Comment by Gr8z** [comment]
Solved and closed.
