### ISSUE TITLE
Text Alignment 

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#13]
The text alignment is not proper as it appears to be very unorganized and looks bad.
![image](https://cloud.githubusercontent.com/assets/27805889/25295083/21f2a7f0-26f3-11e7-9b48-6b7b2d0002b7.png)
see it looks bad.

**Comment by Gr8z** [comment]
Its only doing it for certain messages, search for this in the templates and look at the categories its doing this in. Check for something unusual in the messages where you see a space like that.
