### ISSUE TITLE
BOT seems to be stupid

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#14]
BOT seems to be stupid as it forgets the question that was asked!
![image](https://cloud.githubusercontent.com/assets/27805889/25295202/b0b18f1a-26f3-11e7-987d-f0b3f711ea49.png)
See it forgets the question.

**Comment by Gr8z** [comment]
Most of the bots on the internet are just like that, even siri. Bot has the capability of remembering answers and topics but not to that extent. 

But please let me know if there is a way to make it smarter.
