### ISSUE TITLE
User Text Box does not clear on its own

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#16]
The user Text box does not clear on its own. It should clear out once the user has send a message, giving the user a clear box to type into, rather than clearing it manually every time the user wants to type anything.

**Comment by SaadAhmadSaddiqui** [comment]
Issue Solved

**Comment by Gr8z** [comment]
When I press the enter key, I hear the windows error sound. Is this something that can be solved?

**Comment by SaadAhmadSaddiqui** [comment]
That is the sound that I added. I'm on it to change it. Adding a click sound.

**Comment by Gr8z** [comment]
I hear the beep sound but also an error sound after that.

**Comment by Gr8z** [comment]
This happens only if I press the enter key, not the send button.

**Comment by SaadAhmadSaddiqui** [comment]
I'll look into it.

**Comment by Gr8z** [comment]
Textbox clears on its own so, issue solved. For the ENTER key bug, check #1.
