### ISSUE TITLE
REDUCTION??

### ISSUE THREAD

**Issue by snf9718** [Gr8z/ChatBotProject#17]
What is the "REDUCTION" that appears between conversations very frequently???
![image](https://cloud.githubusercontent.com/assets/27805889/25295455/9902f95c-26f4-11e7-9000-9a1de1a8bea4.png)

**Comment by Gr8z** [comment]
No clue, check the templates. Let me know what you find.

**Comment by snf9718** [comment]
This issue seems to be solved!
But i want everyone to test out the bot and please notify me if the REDUCTION keyword appears again.
Hopefully it wont appear again.

**Comment by Gr8z** [comment]
If you ever encounter random REDUCTION word pop up in chat, take a screenshot and post it here please

**Comment by Gr8z** [comment]
Looks like it's fixed, nice work @snf9718
