### ISSUE TITLE
mention code dependencies in readme.md

### ISSUE THREAD

**Issue by fanbyprinciple** [Gr8z/ChatBotProject#35]
![Screenshot (14)](https://user-images.githubusercontent.com/29324589/185732570-a0c5c742-ad79-4083-8fca-7795872b1ba8.png)

Documentation especially reagrding aiml folder and config folder is required because without them the build breaks. On top : the project generated file. Below : the files in debug folder on github.

**Comment by Gr8z** [comment]
Hi there,

You are welcome to send a PR. I am unable to maintain this repository at this stage.

Thanks.

**Comment by fanbyprinciple** [comment]
Hello, I made changes in readme and adding a pull request
