### ISSUE TITLE
a nice sound when you send the message to the bot

### ISSUE THREAD

**Issue by Gr8z** [Gr8z/ChatBotProject#4]
Something like bloop or beep when you send a message.

**Comment by Gr8z** [comment]
I like the imessage send sound on iPhone, @SaadAhmadSaddiqui are you still working on this ?

**Comment by SaadAhmadSaddiqui** [comment]
Added iMessage send sound.

**Comment by Gr8z** [comment]
Perfect, working as intended, great work! 👍
