### ISSUE TITLE
You can send empty messages to the bot

### ISSUE THREAD

**Issue by Gr8z** [Gr8z/ChatBotProject#5]
Make the user unable to send the message, if the chatbox is blank or filled with spaces.

**Comment by SaadAhmadSaddiqui** [comment]
I managed to make the user unable to send if it is empty but spaces is an issue I'm facing. See if you can manage something.

**Comment by Gr8z** [comment]
Using this fixed the issue
`(string.IsNullOrWhiteSpace(InputTxt.Text)`
